os: linux-ppc64le
sudo: required

script:
  - wget https://oplab9.parqtec.unicamp.br/pub/ppc64el/docker/version-19.03.1/ubuntu-xenial/docker-ce-cli_19.03.1~3-0~ubuntu-xenial_ppc64el.deb
  - wget https://oplab9.parqtec.unicamp.br/pub/ppc64el/docker/version-19.03.1/ubuntu-xenial/docker-ce_19.03.1~3-0~ubuntu-xenial.dsc
  - wget https://oplab9.parqtec.unicamp.br/pub/ppc64el/docker/version-19.03.1/ubuntu-xenial/docker-ce_19.03.1~3-0~ubuntu-xenial.tar.gz
  - wget https://oplab9.parqtec.unicamp.br/pub/ppc64el/docker/version-19.03.1/ubuntu-xenial/docker-ce_19.03.1~3-0~ubuntu-xenial_ppc64el.changes
  - wget https://oplab9.parqtec.unicamp.br/pub/ppc64el/docker/version-19.03.1/ubuntu-xenial/docker-ce_19.03.1~3-0~ubuntu-xenial_ppc64el.deb
  - sudo chmod 777 docker-ce-cli_19.03.1~3-0~ubuntu-xenial_ppc64el.deb
  - sudo chmod 777 docker-ce_19.03.1~3-0~ubuntu-xenial_ppc64el.deb
  - sudo dpkg -i docker-ce-cli_19.03.1~3-0~ubuntu-xenial_ppc64el.deb
  - sudo dpkg -i docker-ce_19.03.1~3-0~ubuntu-xenial_ppc64el.deb
  - sudo docker run hello-world
