env:
  global:
    - FTP_USER='docker'
    - secure: "XV1xLs14DfKzGkCP1mHMLCmbPOQz6orOUujB7UGzsGV78wiZ7nJ1mmEu+LDQoAQLYmopIK/w0LNXdXhITDoRsr2BJSuq/5opIRY/MTDh5KIJQuTj7vAkVhwO0+4VHetIAipD8ID7G7TEyGlfixBF9vOg1crG/++WhcibjmRN2ckLIrqTmbC4gLv/56321/heHhZJmEX4xVy+/9E7MbU/gNvxWELQw2W8tKeo3RnEGpjSw3PSNdOCvFGQQ2PffhXWi2XEiZW0yDfR27vkrdX49zPKGPy5bLccafbhTYFyvhY3UUc2IjEzME6PtdgnQeyOqS6DmrINZUTxhrg6m6PH1JL8Qte+rCg6rYBiASVB1+2o8sFqFC6JFFNdrt868w67XGbbwdoOPccMwfONSKImGbVac3BTw3DvsWMWsT4qoVO9tapcclCbCPULbCCh7BZL25zHMzu+9Za/fDdzjU+KHlQ0dypOIQNeM4YqAl59XzTweJLBZcrZiPDp25yKeHDWzmv/hSdoZV9qT7PRcfKB/qcnzdf0D/t8lufrqRq125p0T2iLvuoOs554R7LQYZAdz8E0orG8ngsZgjXq40qIZlhyJDRDS4Uzl+M6A7sIxBv6b0xsUWDudvUc0tS7C/H1TeY79ji15frWHTISHiQRkr9cD7v37b+peCnGcEBpa94="


language: bash

os: linux-ppc64le

sudo: required

services: docker

script:
  - git clone https://github.com/Unicamp-OpenPower/docker-ce
  - cd ./docker-ce
  - git checkout -t origin/v18.06.2-ce-ppc64le
  - git config --local user.name "Unicamp OpenPower Lab"
  - git config --local user.email "openpower@ic.unicamp.br" 
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - cd components/packaging/rpm
  - VERSION=18.06.2-ce make centos
  - cd ../../../
  - cd components/packaging/deb
  - VERSION=18.06.2-ce make ubuntu-xenial
  - VERSION=18.06.2-ce make ubuntu-bionic 
  - cd ../../../
  - ls components/packaging/deb/debbuild/
  - ls components/packaging/rpm/rpmbuild/RPMS/ppc64le/
  - sudo apt update
  - sudo apt install -y lftp
  - ${TRAVIS_BUILD_DIR}/ftp_upload.sh 'components/packaging/deb/debbuild/' '/ppc64el/docker/deb'
  - ${TRAVIS_BUILD_DIR}/ftp_upload.sh 'components/packaging/rpm/rpmbuild/RPMS/ppc64le/' '/ppc64el/docker/rpm'

