language: bash
os: linux-ppc64le
sudo: required
services: docker

script:
  - git clone https://github.com/docker/docker-ce
  - cd docker-ce/components/packaging/rpm
  - VERSION=current make centos
  - cd ../../../
  - cd components/packaging/deb
  - VERSION=18.09.4 make ubuntu-xenial
  - VERSION=18.09.4 make ubuntu-bionic 
  - VERSION=18.09.4 make debian-stretch
