matrix:
  include:
  - env: sys=debian-stretch dir=docker-ce/components/packaging/deb
  - env: sys=ubuntu-xenial dir=docker-ce/components/packaging/deb
  - env: sys=ubuntu-bionic dir=docker-ce/components/packaging/deb
  - env: sys=centos dir=docker-ce/components/packaging/rpm

os: linux-ppc64le
sudo: required
services: docker

script:
   - git clone https://github.com/docker/docker-ce
   - cd $dir
   - VERSION=1 make $sys
